on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: edunick
        password: Lunyhermosa2016
        repository: edunick/githubaction
        tag_with_ref: true
        tag_with_sha: true
        tags: asd